language:
  - python

python:
  - 3.4

install:
  - pip install pytest-cov
  - pip install python-coveralls

script:
  - py.test -vv exercises.py --cov exercises
  - coveralls

notifications:
  email: false
